### PR TITLE
Fixes the "php artisan migrate:refresh" error.

### PR DESCRIPTION
**Pull request by dragonfire1119**
You can't drop columns after you already deleted the table.

### CODE REVIEW

**Comment by tylercd100** [comment]
This problem is unique to your own setup. Please edit the migration file that was copied over when your ran `php artisan vendor:publish`. 

It will be located at: `/var/www/your_laravel_project/database/migrations/2016_03_27_000000_add_user_data_and_url_to_lern_tables.php`

**Comment by dragonfire1119** [comment]
@tylercd100 Hows this unique to my own setup I tested this over and over with a fresh install of Laravel 5.2.
1. Your "CreateLernTables" class calls to down which calls the drop. So this totally gets rid of the table and all the columns.
2. Your "AddUserDataAndUrlToLernTables" class calls the down which is trying to get rid of the columns but there isn't a table. So it errors out with a sql error.

I did edit the migration but thought that other people would in counter the error so I thought I would help out.

Am I missing something or is a fresh install defective?

**Comment by tylercd100** [comment]
Ok, so I setup a fresh install too and ran these commands with no errors:

``` bash
$ php artisan migrate
Migration table created successfully.
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2016_03_17_000000_create_lern_tables
Migrated: 2016_03_27_000000_add_user_data_and_url_to_lern_tables
```

``` bash
$ php artisan migrate:refresh
Rolled back: 2016_03_27_000000_add_user_data_and_url_to_lern_tables
Rolled back: 2016_03_17_000000_create_lern_tables
Rolled back: 2014_10_12_100000_create_password_resets_table
Rolled back: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2016_03_17_000000_create_lern_tables
Migrated: 2016_03_27_000000_add_user_data_and_url_to_lern_tables
```

Can you give me an error log so I can help you resolve this?

**Comment by dragonfire1119** [comment]
```
 [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1 no such column: user_id (SQL: CREATE TEMPORARY TABLE
  __temp__vendor_tylercd100_lern_exceptions AS SELECT id, class, file, code, status_code,
   line, message, trace, created_at, updated_at, user_id, url, method FROM vendor_tylercd
  100_lern_exceptions)



  [PDOException]
  SQLSTATE[HY000]: General error: 1 no such column: user_id
```

Ok I've tested it more and sqlite is the problem. MySQL works. 

I guess it's a problem if somebody uses sqlite I like to use sqlite because it's faster for testing and development.

**Pull request closed without merging**
