### PR TITLE
Laravel 7

### PR DESCRIPTION
**Pull request by robbielove**
@tylercd100 I have spent hours/days trying to get this to work but its a bit hard with the other packages

### CODE REVIEW

**Comment by robbielove** [comment]
fixes #74

**Comment by robbielove** [comment]
this is the result:

> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Tylercd100\LERN\LERN::record() must be an instance of Exception, instance of TypeError given, called in /Volumes/1/dev/appbase/app/Exceptions/Handler.php on line 49 and defined in /Volumes/1/dev/appbase/vendor/tylercd100/lern/src/LERN.php:59
> Stack trace:
> #0 /Volumes/1/dev/appbase/app/Exceptions/Handler.php(49): Tylercd100\LERN\LERN->record(Object(TypeError))
> #1 /Volumes/1/dev/appbase/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(57): App\Exceptions\Handler->report(Object(TypeError))
> #2 /Volumes/1/dev/appbase/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(88): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->report(Object(TypeError))
> #3 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(TypeError))
> #4 {main}
>   thrown in /Volumes/1/dev/appbase/vendor/tylercd100/lern/src/LERN.php on line 59
> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Tylercd100\LERN\LERN::record() must be an instance of Exception, instance of Symfony\Component\ErrorHandler\Error\FatalError given, called in /Volumes/1/dev/appbase/app/Exceptions/Handler.php on line 49 and defined in /Volumes/1/dev/appbase/vendor/tylercd100/lern/src/LERN.php:59
> Stack trace:
> #0 /Volumes/1/dev/appbase/app/Exceptions/Handler.php(49): Tylercd100\LERN\LERN->record(Object(Symfony\Component\ErrorHandler\Error\FatalError))
> #1 /Volumes/1/dev/appbase/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(57): App\Exceptions\Handler->report(Object(Symfony\Component\ErrorHandler\Error\FatalError))
> #2 /Volumes/1/dev/appbase/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(88): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->report(Object(Symfony\Component\ErrorHandler\Error\FatalError))
> #3 /Volumes/1/dev/appbase/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(130): Illuminate in /Volumes/1/dev/appbase/vendor/tylercd100/lern/src/LERN.php on line 59
> Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

**Comment by tortuetorche** [comment]
Hi @robbielove,

Any news on this pull request?

Have a good day,
Tortue Torche

**Comment by robbielove** [comment]
Not that I am aware of, I am considering abandoning the use of it in my apps

**Comment by tortuetorche** [comment]
Alright, did you use a similar package for your apps?

**Comment by robbielove** [comment]
I haven't really explored the options but I'd suggest you look at sentry.io

**Comment by robbielove** [comment]
I am abandoning this and using sentry.io

**Comment by tortuetorche** [comment]
Hi folks,

@robbielove I've updated your initial work to support Laravel 7 (and also 6 and 8!)
Tests are passing now 🎉.
I also tested LERN with a fresh Laravel 8 application and also an older Laravel 6 application 👍

I'll create pull requests _soon™_ to this repository and its dependencies.

But for early testers, you can do this in the `composer.json` file of your Laravel application:
```javascript
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/tortuetorche/lern"
        },
        {
            "type": "vcs",
            "url": "https://github.com/tortuetorche/monolog-mailgun"
        },
        {
            "type": "vcs",
            "url": "https://github.com/tortuetorche/monolog-sms"
        },
        {
            "type": "vcs",
            "url": "https://github.com/tortuetorche/laravel-notify"
        }
    ],
    "require": {
        //...
        "tylercd100/lern": "dev-next"
    },
    //...
}
```
Then run this command in your terminal: `composer require tylercd100/lern:dev-next`

Have a good day,
Tortue Torche

**Comment by tylercd100** [comment]
Merged #78 instead

**Comment by tortuetorche** [comment]
Many thanks Tyler!

**Pull request closed without merging**
